[package]
name = "gear_tech_task"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
name = "staff_lib"

[dependencies]
num-traits = "0.2.19"
rand = "0.8"
uuid = { version = "1.11.0", features = ["v4"] }
